### PR TITLE
MCKIN-12207 AF#95-Ensure content updates define focus updates appropriately

### PR DESCRIPTION
**Pull request by nasirhjafri**
MCKIN-12207 AF#95-Ensure content updates define focus updates appropriately

[Issue]
When any of the chat options button is selected, the focus is taken to the top of the page and not to the start of the message that was rendered. Activating the Refesh button places focus on the button and not to the message rendered.

[User Impact]
Assistive technology users such as screen reader users, users with mobility impairments using keyboard only or users using magnification software may be confused by the change in focus. They may have to review the page to find out what changed which may make navigation confusing and time-consuming.

[Recommendations]
Developers must ensure that programmatic focus is taken to the start of the newly updated message that was rendered and not to the top of the page or the refresh button in the case when refresh button is activated.

### CODE REVIEW

**Comment by nasirhjafri** [comment]
@xitij2000 Please review this.

**Comment by Agrendalath** [comment]
@nasirhjafri, thank you for the contribution. I'll review this PR tomorrow.

**Comment by Agrendalath** [comment]
ezgif-3-26aa505c2130

@nasirhjafri, I tested this in Studio and it focuses on the correct message after clicking a response button. However I'm not able to `Tab` between other messages - when I press `Tab`, the focus is going directly to the response button. Pressing `Shift+Tab` from there focuses on the "delete component" button, though. Is making the `Tab` navigation possible a part of another ticket? I presented this problem below:

gif2

**Comment by nasirhjafri** [comment]
@Agrendalath Since messages don't have any events bound with them, we don't need to focus them using the keyboard. We are only changing focus (only with JS) so that magnification software can take their focus at the new message too.

**Comment by Agrendalath** [comment]
:+1:

- [x] I tested this: tested that focus is on the new message after pressing the response button
- [x] I read through the code
- [x] I checked for accessibility issues
- [ ] <s>Includes documentation</s>

**Review by Agrendalath — APPROVED** [review]

**Pull request merged**
