### PR TITLE
MCKIN-8439: right align text in chat bubble for rtl languages

### PR DESCRIPTION
**Pull request by msaqib52**
@xitij2000 can you review this PR?

### CODE REVIEW

**Comment by xitij2000** [comment]
@msaqib52 This change is working well, however I noticed that the [notice text and icon](https://github.com/open-craft/xblock-chat/blob/d7856a3806b03e37d068b69263fcf76330f4a84a/chat/public/js/src/chat.js#L24-L290) are still incorrectly aligned in rtl mode, i.e. the icon is on the right and text on the right, and the text is left-aligned. 

While you are at it could you fix that as well?

**Comment by msaqib52** [comment]
@xitij2000 Thank you for pointing that out, i have updated this PR with fix for notice text

**Review by xitij2000 — APPROVED** [review]
:+1:

- [x] I tested this: manual testing of block in LMS
- [x] I read through the code
- [na] I checked for accessibility issues
- [na] Includes documentation

**Comment by msaqib52** [comment]
@xitij2000 could you also create a release for this change, so we can update it on platform.

**Comment by xitij2000** [comment]
@msaqib52 Sorry for not noticing this but this PR didn't include a version bump. Could you make a quick PR that bumps the version to 0.2.2. I will make a release from that.

**Pull request merged**
