### PR TITLE
Fixed images of bot and user

### PR DESCRIPTION
**Pull request by murad-hubib**
- Fixed direction of user and bot images in webview of IOS

Issue: [https://edx-wiki.atlassian.net/browse/MCKIN-8273](https://edx-wiki.atlassian.net/browse/MCKIN-8273)

Please review the PR
@xitij2000  @bradenmacdonald

### CODE REVIEW

**Comment by xitij2000** [comment]
@murad-hubib Could you increment the patch version in ``setup.py`` as well?

**Review by xitij2000 — APPROVED** [review]
:+1: once this includes a version bump. 
- [x] I tested this: manually tested the xblock to see if the blocks as described in rtl context.
- [x] I read through the code
- [na] checked for accessibility issues
- [na] Includes documentation

**Comment by xitij2000** [comment]
@murad-hubib Could you bump it to 0.2.1 instead since this is a bug fix?

**Comment by murad-hubib** [comment]
@xitij2000 Can you please squash and merge the commits?

**Pull request merged**
