### PR TITLE
MCKIN-13354 Fix restart button

### PR DESCRIPTION
**Pull request by moeez96**
Jira Ticket: https://edx-wiki.atlassian.net/browse/MCKIN-13354

Issue: When user clicks on a new message, and then clicks on the restart button before the message (or its reply by the xblock) has been posted, the restart button does not clears all messages and results in a jerky UX.

Solution: This happens when the restart button is clicked before the [promise for adding a new message](https://github.com/open-craft/xblock-chat/blob/28cfc7c8ba70e1be314e5233ab1d287a0b164b7a/chat/public/js/src/chat.js#L684) has resolved. The restart button clears messages but the promise has not resolved yet and adds the messages again. Ideally, the restart button should be hidden like other buttons when a new message is being added on the xblock, and shown to the user when promise has successfully resolved.

### CODE REVIEW

**Comment by moeez96** [comment]
@xitij2000 Please review, merge and tag.

**Comment by Agrendalath** [comment]
Thank you for the change, @moeez96!
I tested this locally and it works like expected.

I noticed that the CI was not enabled for PRs created from forks, so I enabled it in CircleCI and triggered it [manually](https://discuss.circleci.com/t/api-trigger-build-of-pull-request-from-fork/7784/18). Could you please fix the failing tests?

**Comment by moeez96** [comment]
@Agrendalath Sure, working on it.

**Comment by moeez96** [comment]
@Agrendalath Please review
If approved, please merge and create release tag,
Since I do not have access.

**Review by Agrendalath — APPROVED** [review]
:+1:
* [x]  I tested this: tested that the reset button does not appear when it's not user's turn
* [x]  I read through the code
* [ ]  <s>I checked for accessibility issues</s>
* [ ]  <s>Includes documentation</s>

**Comment by Agrendalath** [comment]
@moeez96, done, thank you for fixing this :)

**Pull request merged**
